#! /bin/sh

# autostart
pgrep -x sxhkd > /dev/null || sxhkd &
~/.config/eww/bar/launch_bar
/usr/bin/eww -c ~/.config/eww/widgets kill
/usr/bin/eww -c ~/.config/eww/widgets daemon

# monitor
bspc monitor eDP-1 -d 1 2 3 4 5 6

# extended monitors
bspc monitor HDMI-1 -d 1 2 3 4 5 6 
bspc monitor DP-1 -d 1 2 3 4 5 6 

# window information
bspc config border_width         2
bspc config window_gap          16

bspc config split_ratio          0.52
bspc config pointer_follows_monitor   true
bspc config focus_follows_pointer      true

# rules
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Spotify desktop='^5' state=floating
