#!/bin/bash

volume=$(pulsemixer --get-volume | cut -d' ' -f1)
muted=$(pulsemixer --get-mute)

if [[ $muted -eq 1 ]] ; then
    icon=""
    text="${volume}"
    col="#575268"
elif [[ $volume -le 50 ]] ; then
    icon=""
    text="${volume}"
    col="#a1bdce"
else
    icon=""
    text="${volume}"
    col="#a1bdce"
fi

if [[ "$1" == "--COL" ]]; then
  echo $col	
elif [[ "$1" == "--VOL" ]]; then
	echo $text
elif [[ "$1" == "--ICON" ]]; then
	echo $icon
fi
