#!/bin/bash

## Files and cmd
FILE="$HOME/.cache/eww_launch_side.xyz"
EWW="/usr/bin/eww -c $HOME/.config/eww/leftbar_old_pls_dont_use"

# windows not in use
# exit

## window list
w_ls="
    back \
    status \
    time \
    clse \
    day_dot \
    sys_usg \
    song \
    fetch \
    pfp
"
## Run eww daemon if not running already
if [[ ! `pidof eww` ]]; then
	${EWW} daemon
	sleep 1
fi


## Open widgets 
run_eww() {
    ${EWW} open-many $w_ls
}

## Launch or close widgets accordingly
if [[ ! -f "$FILE" ]]; then
	touch "$FILE"
	run_eww 
else
    ${EWW} close $w_ls 
	rm "$FILE"
fi
